### ISSUE TITLE
How to use this software?

### ISSUE THREAD

**Issue by systracing2** [redcanaryco/redcanary-ebpf-sensor#37]
I can successfully compile this software via docker compose. And got a list of share objects:

`systracing2@ubuntu:~/redcanary-ebpf-sensor/build/x86_64$ ls -rlt
total 308
drwxr-xr-x 2 root root   4096 Feb  7 23:23 wrapped
-rw-r--r-- 1 root root  10320 Feb  7 23:23 wpm-events
-rw-r--r-- 1 root root   9856 Feb  7 23:23 pam-events
-rw-r--r-- 1 root root 185248 Feb  7 23:23 process-events
-rw-r--r-- 1 root root  18456 Feb  7 23:23 network-events
-rw-r--r-- 1 root root  13360 Feb  7 23:23 cred-events
-rw-r--r-- 1 root root  59928 Feb  7 23:23 script-events`

IIUC I need to create my main function to use these library since I didn't find `main` function. Thank you!

**Comment by RafaelOrtizRC** [comment]
Hey there! This repo is just the BPF programs without any loaders. We did this so we wouldn't be tied to any one specific loader, such as BCC, since they tend to do some preprocessing and other undesirable things.

The BPF programs in this repo are typically loaded with [`oxidebpf`](https://github.com/redcanaryco/oxidebpf). Let's say you want to use the `process-events` program, on a Linux kernel version that wraps syscalls (should be any modern one). We can adapt the example from `oxidebpf` as follows.

```
let program = PathBuf::from("~/redcanary-ebpf-sensor/build/x86_64/wrapped/process-events);
let program_blueprint =
    ProgramBlueprint::new(&std::fs::read(program).expect("Could not open file"), None)
        .expect("Could not open test object file");
let mut program_group = ProgramGroup::new();
let (tx, rx) = crossbeam_channel::bounded(1024);

program_group.load(
    program_blueprint,
    vec![ProgramVersion::new(vec![
        Program::new(
            "sys_fork",
            vec!["sys_fork"],
        )
        .syscall(true),
    ])],
    || (tx, PerfBufferSize::Total(4096))),
).expect("Could not load programs");

// read from rx any events from a perfmap in the loaded program version
```

Now we can use the crossbeam channel's receiving side (`rx`) to read channels emit by the BPF program, whenever a fork occurs. 

Note that there are a few macros and functions in there that make reference to `offsets`. See the section of [this blog post](https://redcanary.com/blog/ebpf-for-security/) about "A GPS for the Linux Kernel." In short, we need a consistent way to navigate kernel structs on systems that don't support [BTF](https://www.kernel.org/doc/html/latest/bpf/btf.html). We can do this by building and extracting structure offsets ahead of time, and loading them into our BPF programs at runtime. The BPF programs will check a map for offsets and use those offsets to navigate and get data from the kernel. Open source release coming soon (I hope). 

In any case, you can use the test program in the `oxidebpf` repo as a template for building and loading your own BPF programs.

**Comment by RafaelOrtizRC** [comment]
I'm going to close this out. Please let us know if you have any more questions.
